build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.21
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.21
labels:
  org.opencontainers.image.title: Seiden Vision
  org.opencontainers.image.description: Plataforma local de análise de imagens
  org.opencontainers.image.source: https://github.com/eduseiden/Seiden_Vision
  org.opencontainers.image.licenses: MIT
args:
  TEMPIO_VERSION: "2024.11.2"
